### PR TITLE
WIP: Fix Scrutinizer and SymfonyInsight

### PR DESCRIPTION
**Pull request by freezy-sk**

### CODE REVIEW

**Comment by curry684** [comment]
Mmm I already did this I think?   😉

**Comment by curry684** [comment]
https://github.com/omines/datatables-bundle/commit/8cb8ce0bc72667d940cc6082024d62cfb0a2063d

**Comment by freezy-sk** [comment]
@curry684 I know, but it's a hack. This bundle does not depends on ocramius/package-versions so it shouldn't be there just to solve problems of CI platforms.

**Comment by curry684** [comment]
Agreed from a purist view but I didn't really bother because it's only needed in dev dependencies (and I also wasted an hour before, trying to fix it better to no avail).

**Comment by curry684** [comment]
Scrutinizer is fixed and I remove Symfony Insights as it had no added value anyway anymore.

Still thanks for the effort  👍

**Pull request closed without merging**
