### PR TITLE
test: add GitHub Actions

### PR DESCRIPTION
**Pull request by Chris53897**
Provide basic tests in GitHub Actions.

This needs improvments. But iin the actual state it already can help developers to run there PR against tests.

### CODE REVIEW

**Comment by Ahummeling** [comment]
I would like to bring to your attention that the successful php8.0 and php8.1 tests seem to be false positives. 
https://github.com/Chris53897/datatables-bundle/runs/4731077536?check_suite_focus=true
The tests are never executed, because simple-phpunit tries to install a phpunit version that is compatible with the phpunit-bridge (v4.4.9) and the php version (8.0.13), however, no such version exists (that would be 9.5 or something, but 8.3 is the latest version supported by the symfony bridge).

**Comment by Chris53897** [comment]
You are right . The --prefer-lowest tag should be only added for the lowest supported php version.

**Comment by maxhelias** [comment]
The "symfony/phpunit-bridge" does not need to have different version support, i think just remove the "^4.4" support for this package should be fix this

**Comment by Ahummeling** [comment]
Actually, considering this from [phpunit_bridge documentation](https://symfony.com/doc/current/components/phpunit_bridge.html#installation)

> The PHPUnit bridge is designed to work with all maintained versions of Symfony components, even across different major versions of them. You should always use its very latest stable major version to get the most accurate deprecation report.

Perhaps it is wise to even pin it to `^6.0`, what do you guys think?

**Comment by maxhelias** [comment]
> Perhaps it is wise to even pin it to ^6.0, what do you guys think?

I agree with that 👍

**Comment by Chris53897** [comment]
This is just a basic workflow i copied and adjusted it a bit. quick and dirty to help with the symfony6 support. 
Maybe i should close the PR after that happened. Or if i find the time, i will improve it.

**Comment by curry684** [comment]
Migration to Github Actions is done, however it does still need to be expanded to run for example the `--prefer-lowest` tests and allow failures in 8.2.

I'll keep this open as a WIP.

**Pull request closed without merging**
