### PR TITLE
Introduced the possibility to implement a client-side table

### PR DESCRIPTION
**Pull request by giovannialbero1992**
See issue #6

### CODE REVIEW

**Comment by curry684** [comment]
I'm sorry I didn't get a chance to properly provide feedback on this yet. It's a pretty invasive feature and I'll have to properly think through whether the approach taken is the best for future extensions.

**Comment by giovannialbero1992** [comment]
For my intents is very useful this feature.
For the moment I'm using my fork for production environments.
I hope to see a feature that introduces a feature like this in the next releases.
I'd like to provide my contribution to this project.

**Comment by curry684** [comment]
Closing due to inactivity, it seems there's not much demand for this feature.

**Comment by giovannialbero1992** [comment]
Ok @curry684 , someone has forked my fork to use this feature.
I hope that you keep in mind for the future.
Thanks
G.

**Comment by curry684** [comment]
Of course :)

**Pull request closed without merging**
