### PR TITLE
Datatable generation command for creating datatables automatically

### PR DESCRIPTION
**Pull request by adsazad**
Symfony command to create datatables automaticaly to reduce time consumption in creating datatable.
this command will generate skeleton for datatable as given in this datatable's documentation.
It simply works by running command:
`php bin/console datatables:generate`
which is followed by questions like the Controller where you want to put action and name of twig and the route to be generated
this will automatically generate route, action, and twig and your datatable will be ready to go in seconds.
the code is completely tested.

### CODE REVIEW

**Comment by adsazad** [comment]
Hay did you see it.

**Comment by maxhelias** [comment]
Why not create a maker bundle commande to create a new service that implements `DataTableTypeInterface` ?

**Comment by adsazad** [comment]
i don't know.
what i had on my minde i made it.

**Comment by curry684** [comment]
I agree this should not be core functionality of the bundle, developer-only functionality shouldn't be part of the deployable code. Suggestion from @maxhelias sounds like a much better idea.

**Pull request closed without merging**
