### PR TITLE
feat: add Searchable UuidColumn

### PR DESCRIPTION
**Pull request by Chris53897**
This is working for us. I guess it would be useful for others as well.
I am not sure if extend from TextColumn is ok for the generic case in this bundle.

### CODE REVIEW

**Comment by curry684** [comment]
This seems to address an extremely limited scenario in which you want to invisibly add a row's UUID to a datatable for the single purpose of being able to search by (partial) ID?

**Comment by Chris53897** [comment]
We Link our Entities over the uuid from a datatable to another datatable. Every entity has a toString() or getDatatableLink() who returns `/user/list#search[search]=UUID` (wrapped in an <a> tag).
Like a Posts-Datatable has a User. The link is generated to the filtered Dataset in der User-Datatable.
A little bit like in your comment here about HyperLinkColumn. https://github.com/omines/datatables-bundle/issues/290#issuecomment-1431130934

And i like to see/copy the UUID easily as a helper to look things up in the database.

I can close this PR, as if you think it belongs to the userspace.

**Comment by Chris53897** [comment]
Partial-Search because we use only a part of the UUID at customer side.

**Comment by curry684** [comment]
Yeah I gathered as much, I'd recommend keeping this in userspace, the general applicability is highly limited  :)

**Pull request closed without merging**
