### PR TITLE
Add result transformer

### PR DESCRIPTION
**Pull request by danut007ro**
This pull request aims to add a result transformer that behaves just like the row transformer (formatter).

It allows to do a post-processing for entire result, not only for a row.
I use it for a custom PromiseColumn where I collect all the rows and make a single call to database to get result for each row, instead of making as many calls as rows.

I couldn't find any other way of having this functionality and it looks useful. Tests included.

Thanks.

### CODE REVIEW

**Comment by curry684** [comment]
What case does this solve that the regular `transformer` option doesn't already provide?

**Comment by danut007ro** [comment]
The regular transformer doesn't allow to process the entire result in bulk, only one by one. In my case I needed the bulk processing to use promises.

**Comment by danut007ro** [comment]
Oh I see. I will try the `LazyDataAdapter` way. Unfortunatelly that will be mostly copy-pasted from `ORMAdapter` and also `AbstractAdapter` (close to 100% + my transformer code). That's why I was searching for an alternative solution.

**Comment by curry684** [comment]
No you wouldn't need to copy/paste much, just implement a [Decorator](https://en.wikipedia.org/wiki/Decorator_pattern):
```
class LazyAdapter implements AdapterInterface
{
    private $wrapper;

    public function __construct(AdapterInterface $wrapper)
    {
        $this->wrapper = $wrapper;
    }

    public function configure(array $options)
    {
        $this->wrapper->configure($options);
    }

    public function getData(DataTableState $state): ResultSetInterface
    {
        $dataset = $this->wrapper->getData($state);
        foreach ($dataset->getData() as $row) {
            // Do stuff
        }
        return $dataset;
    }
}
```

**Comment by danut007ro** [comment]
Thank you. Will try and see how it goes. This will be my last pull request related to result transformers, I promise :)

**Pull request closed without merging**
