### PR TITLE
Add opcache preloading support

### PR DESCRIPTION
**Pull request by trandbert37**
Fixing #196

### CODE REVIEW

**Review by maxhelias — APPROVED** [review]

**Comment by curry684** [comment]
Out of curiosity: why does this fix the issue? Shouldn't opcache preloading support anonymous classes?

The fix seems fine but well, it was inline for a reason.

**Comment by trandbert37** [comment]
It seems to be a php bug and was fixed in php 7.3.13

**Comment by curry684** [comment]
Ok but 7.3.13 was released a year ago on Dec 18 2019 and and 7.3 as a whole will go EOL [in 8 days](https://www.php.net/supported-versions.php). So I don't really see a reason to fix it in our codebase now?

**Comment by trandbert37** [comment]
Sorry, I meant 7.4.13

**Comment by pkly** [comment]
> Sorry, I meant 7.4.13

so it's a fix for a bug fixed already?

**Comment by curry684** [comment]
Not merging a fix for a single minor PHP release which was already fixed in upstream.

**Pull request closed without merging**
