### PR TITLE
Use trans() for proper locale fallback when using CDN languages

### PR DESCRIPTION
**Pull request by freezy-sk**
@jkabat mentioned in #136 that he uses fr_FR as locale. this update should fix this issue when cdn language is configured with supported locale, but used with defined region

### CODE REVIEW

**Comment by curry684** [comment]
This makes sense I think, but doesn't this also require an update to https://github.com/omines/datatables-bundle/blob/master/bin/update-translations to avoid it removing the `file` properties next time it's run?

**Comment by freezy-sk** [comment]
@curry684 there's no need to update that script, because `file` property is in own file `DataTablesCDN.{locale}.yml`

**Comment by curry684** [comment]
@shades684 whatcha think?

**Comment by curry684** [comment]
@freezy-sk could you check why it breaks all tests? Master branch is passing right now (don't think it was when you started this).

**Comment by freezy-sk** [comment]
@curry684 I squashed and rebased but it's still failing on ocramius/package-versions

**Comment by curry684** [comment]
Yep, started breaking again in `master` as well  😕

**Comment by curry684** [comment]
👍

**Pull request merged**
